# Generated by Django 5.0.6 on 2024-06-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/imgres?q=placeholder%20food%20image&imgurl=https%3A%2F%2Flivingstonbagel.com%2Fwp-content%2Fuploads%2F2016%2F11%2Ffood-placeholder.jpg&imgrefurl=https%3A%2F%2Feverestkitchenpa.com%2Fassets%2Fpages%2FcoldBeverages.html&docid=We3NgZm0lWOZuM&tbnid=Ag1_-7HSofts3M&vet=12ahUKEwiX0PX0oL6GAxWSxTgGHf8qCxwQM3oECHUQAA..i&w=499&h=374&hcb=2&ved=2ahUKEwiX0PX0oL6GAxWSxTgGHf8qCxwQM3oECHUQAA', max_length=1000),
        ),
    ]
