# Generated by Django 5.0.6 on 2024-06-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_name',
        ),
    ]
